#### 2. ndarray 확인하기 > 함수가 아닌 "속성"

In [2]:
import numpy as np

In [1]:
list1 = [1,2,3,4,5]
list2 = [[1,2],[3,4],[5,6]]

In [3]:
arr1 = np.array(list1)
arr2 = np.array(list2)

In [4]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [6]:
# 배열의 모양 확인하기
print(arr1.shape)
print(arr2.shape)

(5,)
(3, 2)


In [23]:
arr1 = [[[1,2],[3,4]],[[5,6],[7,8]]]
arr2 = np.array(arr1)
arr2
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)

(2, 2, 2)
3
8


#### ndarray dtype 변경, shape 변경

In [33]:
list4 = [[1.7,4.2,3.6],[4.1,2.9,5.8]]

temp1 = np.array(list4)
temp2 = np.array(list4, dtype=np.int64)

print(temp1)
print(temp1.dtype)
print()
print(temp2)
print(temp2.dtype)

[[1.7 4.2 3.6]
 [4.1 2.9 5.8]]
float64

[[1 4 3]
 [4 2 5]]
int64


In [ ]:
temp2 = temp2.astype(dtype = np.float64)

In [ ]:
# 배열의 특정 크기로 변경
# reshape


In [44]:
# 모든 값을 0으로 초기화(생성)
# zeros()

arr_zeros = np.zeros((5,5))
arr_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
# 모든 값을 1로 초기화
# ones

arr_ones = np.ones((5,5))
arr_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
#원하는 값으로 배열 초기화
# full

arr_full = np.full((3,3),10)
arr_full

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [50]:
#실습 : 1~50까지 담긴 1차원 array 생성
a = list(range(1,51))
array = np.array(a)
array
print(array.shape)
print(array.dtype)

(50,)
int32


In [52]:
array1 = np.arange(1,51)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

#### ndarray 연산
- 요소별 연산에 특화
- 브로드 캐스팅 지원(차원을 동일시 하는 기능)

In [55]:
arr1 = np.arange(1,6)
arr2 = np.arange(6,11)

print(arr1)
print(arr2)
arr1 + arr2

[1 2 3 4 5]
[ 6  7  8  9 10]


array([ 7,  9, 11, 13, 15])

In [ ]:
arr_a = np.array([[1,2,3],[4,5,6]])
arr_b = np.array([[1,2,3],[4,5,6]])

print(arr_a)
print(arr_b)
arr_a + arr_b


'applepen'

In [54]:
string = "aBcDeFg"

for i in string:
    if i.isupper() == True:
        print(i.lower(),end="")
    else:
        print(i.upper(), end="")
        

AbCdEfG