In [1]:
import numpy as np

In [ ]:
#브로드 캐스팅
arr_c = np.array([1,2,3])

#### array 인덱싱 & 슬라이싱
- 인덱싱(indexing) : 값을 가리키다 -> 자료 구조 내에서 1개의 요소에 접근하는 것
- 슬라이싱(slicing) : 값을 잘라오다 -> 자료 구조 내에서 여러개의 요소들에 접근하는 것

#### 2차원 array 인덱싱 슬라이싱
- 인덱싱 : array[행,열]
- 슬라이싱 : array[행시작,:행의끝,열의 시작:열의 끝]

In [30]:
# 2차원 array
arr2 = np.arange(1,51).reshape(5,10)
arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [7]:
arr2[2:,:9]

array([[21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [31]:
#1번쨰
arr2[:2,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [37]:
arr2[range(5),0]

array([ 1, 11, 21, 31, 41])

In [41]:
#2번째
arr3 = arr2[:,:1].reshape(1,5)
arr3


array([[ 1, 11, 21, 31, 41]])

In [32]:
#3번째
arr2[:4,:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35]])

#### 데이터 경로 지정
1. 절대경로
    - "/"로 시작하는 경로
    - 루트 디렉토리에서 시작해서 파일이나 디렉토리 위치를 나타냄.
2. 상대경로
    - "./"로 시작하는 경로
    - 현재 내 위치에서 시작하여 파일이나 디렉토리 위치를 나타냄
    - "../" 경로
    - 현재 내 위치의 상위 디렉토리(부모 디렉토리)를 지정 

In [17]:
# 데이터 읽어오기 (.txt 파일 확장자)
data = np.loadtxt("C:\\Users\\SMHRD\\Desktop\\스인재\\강의내용\\data\\height_weight(p).txt", delimiter=',')



In [25]:
data

array([[175.2   , 180.3   , 175.    , 169.2   , 185.2   , 188.    ,
        177.6   , 178.2   , 177.    , 179.    ],
       [144.5824, 193.952 , 174.5568, 152.7372, 121.22  , 156.9248,
        160.892 , 151.8556, 163.096 , 180.728 ]])

In [45]:
# bmi 지수 구하기
# bmi = 몸무게 / 키*키

height = data[0:1,:]/100
weight = data[1:,:]
weight_kg = (weight/2.204)


bmi = weight_kg / (height**2)

print(bmi)

[[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
  23.14392095 21.69720651 23.62028791 25.59220998]]


### numpy 수학 함수

In [52]:
arr = np.random.randint(1,10,size=(2,5))
arr

array([[1, 8, 9, 5, 8],
       [6, 3, 3, 9, 2]])

In [54]:
arr.sum()
np.mean(arr)

54

In [57]:
np.sqrt(arr)

array([[1.        , 2.82842712, 3.        , 2.23606798, 2.82842712],
       [2.44948974, 1.73205081, 1.73205081, 3.        , 1.41421356]])

| 함수 이름   | 사용법                 | 설명                                | 예시 결괏값 |
|-------------|------------------------|-------------------------------------|-------------|
| `np.add`    | `np.add(x, y)`         | 배열 x와 y의 요소별 합계            | `3, 7, 11`  |
| `np.subtract` | `np.subtract(x, y)`  | 배열 x에서 y를 요소별로 뺀 결과    | `-1, 1, 3`  |
| `np.multiply` | `np.multiply(x, y)`  | 배열 x와 y의 요소별 곱셈            | `2, 10, 24` |
| `np.divide` | `np.divide(x, y)`      | 배열 x를 y로 요소별 나눈 결과       | `0.5, 2, 4` |
| `np.sqrt`   | `np.sqrt(x)`           | 배열 x의 요소별 제곱근              | `1, 2, 3`   |
| `np.exp`    | `np.exp(x)`            | 배열 x의 요소별 e^x 계산            | `2.718, 7.389, 20.086` |
| `np.log`    | `np.log(x)`            | 배열 x의 요소별 자연로그 계산       | `0, 0.693, 1.099` |
| `np.sin`    | `np.sin(x)`            | 배열 x의 요소별 사인 값 계산        | `0.841, 0.909, 0.141` |
| `np.cos`    | `np.cos(x)`            | 배열 x의 요소별 코사인 값 계산      | `0.540, -0.416, -0.990` |
| `np.tan`    | `np.tan(x)`            | 배열 x의 요소별 탄젠트 값 계산      | `1.557, -2.186, -0.143` |

### 불리안 인덱싱(Boolean Indexing)
- 배열 안에서 조건을 충족(특정 조건을 만족)하는 True인 값들만 추출해서 인덱싱하는방법.
- 간단히 말하면, "필터링"을 연상.



In [58]:
score = np.array([80,75,55,96,30])
score

array([80, 75, 55, 96, 30])

In [59]:
mask = score >= 60

In [61]:
score[mask]

array([80, 75, 96])

In [64]:
bmi

array([[21.37153104, 27.07018468, 25.86122449, 24.20652885, 16.03543423,
        20.14486193, 23.14392095, 21.69720651, 23.62028791, 25.59220998]])

In [75]:
bmi >= 23

array([[False,  True,  True,  True, False, False,  True, False,  True,
         True]])

In [74]:
bmi <= 25

array([[ True, False, False,  True,  True,  True,  True,  True,  True,
        False]])

#### and,or 논리연산자와 "&, |"같은 비트연산자의 차이
- 논리(and,or) : 단일 Bool값에서만 비교 가능
- 비트(&,|) : 다중 Bool값에 대해서 개별적으로 각 요소에 대한 T/F를 변환

In [81]:
bmi[(bmi >= 23) & (bmi <= 25)]

array([24.20652885, 23.14392095, 23.62028791])

#### 최종실습! 영화데이터(평점) 분석!

In [93]:
new_rating = np.loadtxt("C:\\Users\\SMHRD\\Desktop\\스인재\\강의내용\\data\\new_ratings.dat",delimiter="|",dtype=np.int64)

In [95]:
movie = new_rating.copy()

In [96]:
movie.shape

(1000209, 4)

| 사용자 ID | 영화 ID | 영화평점(별점) | 입력시간(타임스템프) |
|---------- |--------|---------------|--------------------|

In [101]:
movie

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       ...,
       [     6040,       562,         5, 956704746],
       [     6040,      1096,         4, 956715648],
       [     6040,      1097,         4, 956715569]], dtype=int64)

In [113]:
np.unique(movie[:,:1],return_counts=True)

(array([   1,    2,    3, ..., 6038, 6039, 6040], dtype=int64),
 array([ 53, 129,  51, ...,  20, 123, 341], dtype=int64))

In [116]:
#전체 영화 평점의 평균 추출
a = movie[:,2]
a.mean()
a.mean().round(2)

3.58

In [120]:
# 평점을 매긴 사용자가 총 몇명인지 알아보자!
np.unique(movie[:,0])
len(np.unique(movie[:,0]))

6040

In [121]:
user_id = np.unique(movie[:,0])

#### 각각의 사용자가 매긴 평점의 평균 중에서 4점 이상의 평점만 구하기.
- 이후 csv파일로 저장

In [138]:
user1 = movie[movie[:,0] == 1]
print(user1[:,2].mean())
print(user1)

4.188679245283019
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1      1270         5 9783

In [133]:
for i in movie:
    print(i)
    print(i[0])
    print(i[1])
    break
    

[        1      1193         5 978300760]
1
1193


In [136]:
len(np.unique(movie[:,0]))

6040

In [164]:
# 각각의 사용자가 메긴 평점들의 평균 모두 구해보자!
# list에 담아서 for문 활용
# 평점이 4.0 이상인 아이디만 선별

score_avg = []
for i in range(len(np.unique(movie[:,0]))):
    user_id = movie[movie[:,0] == i]
    user_avg = user_id[:,2].mean()
    if user_avg >= 4.0:
        score_avg.append([i,user_avg])


print(score_avg)      

C:\Users\SMHRD\AppData\Local\Temp\ipykernel_2784\167694505.py:6: RuntimeWarning: Mean of empty slice.
  user_avg = user_id[:,2].mean()
c:\Users\SMHRD\anaconda3\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


[[1, 4.188679245283019], [4, 4.190476190476191], [7, 4.32258064516129], [10, 4.114713216957606], [17, 4.075829383886256], [20, 4.083333333333333], [27, 4.171428571428572], [36, 4.199430199430199], [43, 4.125], [46, 4.219512195121951], [53, 4.2368421052631575], [54, 4.025], [55, 4.12], [64, 4.148148148148148], [65, 4.347107438016529], [67, 4.296875], [69, 4.153846153846154], [74, 4.046511627906977], [75, 4.005714285714285], [76, 4.172413793103448], [81, 4.4186046511627906], [82, 4.016949152542373], [86, 4.3125], [88, 4.147058823529412], [91, 4.704545454545454], [97, 4.474025974025974], [101, 4.679245283018868], [103, 4.052173913043478], [105, 4.295081967213115], [106, 4.0212765957446805], [109, 4.0], [112, 4.183333333333334], [121, 4.416666666666667], [124, 4.173913043478261], [125, 4.098591549295775], [126, 4.0], [128, 4.363636363636363], [129, 4.025316455696203], [130, 4.311111111111111], [138, 4.492307692307692], [150, 4.021551724137931], [152, 4.125], [153, 4.076923076923077], [156,

In [193]:
print(score_avg)

[[1, 4.188679245283019], [4, 4.190476190476191], [7, 4.32258064516129], [10, 4.114713216957606], [17, 4.075829383886256], [20, 4.083333333333333], [27, 4.171428571428572], [36, 4.199430199430199], [43, 4.125], [46, 4.219512195121951], [53, 4.2368421052631575], [54, 4.025], [55, 4.12], [64, 4.148148148148148], [65, 4.347107438016529], [67, 4.296875], [69, 4.153846153846154], [74, 4.046511627906977], [75, 4.005714285714285], [76, 4.172413793103448], [81, 4.4186046511627906], [82, 4.016949152542373], [86, 4.3125], [88, 4.147058823529412], [91, 4.704545454545454], [97, 4.474025974025974], [101, 4.679245283018868], [103, 4.052173913043478], [105, 4.295081967213115], [106, 4.0212765957446805], [109, 4.0], [112, 4.183333333333334], [121, 4.416666666666667], [124, 4.173913043478261], [125, 4.098591549295775], [126, 4.0], [128, 4.363636363636363], [129, 4.025316455696203], [130, 4.311111111111111], [138, 4.492307692307692], [150, 4.021551724137931], [152, 4.125], [153, 4.076923076923077], [156,

In [179]:
data1 = score_avg.copy()

In [207]:
data1 = data1.astype(int)
print(data1)

[[   1    4]
 [   4    4]
 [   7    4]
 ...
 [6027    4]
 [6032    4]
 [6034    4]]


In [209]:
# np.savetxt("경로 및 파일명.확장자",데이터,delimiter="구분자")
np.savetxt("영화평점 분석.csv",data1,delimiter=",")

In [ ]:
#리스트 내포
movie_id = [[movie[movie[:,0]==i][:,2].mean().round(2)] for i in user_id]