#### Numpy 라이브러리
- Numerical Python의 약자
- 수치계산을 위한 핵심 라이브러리

In [1]:
import numpy as np
# import : 외부 라이브러리를 불러올때 사용하는 키워드
# as : alias(별칭)


#### ndarray(N-dimensional array, 다차원배열)
1. 다양한 수학함수를 제공
2. 빠른 연산속도를 제공
3. 브로드 케스팅(차원을 동일시 하는 기능)
4. 다차원의 배열 지원

- 동일한 자료형을 가지는 값들이 배ㅕㄹ 형태로 존재함
- 각 값들의 색인(index) 부여되어 있다.

In [3]:
# ndarray 생성하기
# 1. 첫번째 방법 : 리스트 데이터를 array화 하는 방법
list1 = [1,2,3,4,5]

arr1 = np.array(list1)

In [4]:
type(arr1)

numpy.ndarray

In [6]:
#2차원 ndarray 생성하기
list2 = [[1,2,3,4,5],[1,2,3,4,5]]
arr2 = np.array(list2)

In [7]:
print(list2)
print()
print(arr2)

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [10]:
list1 = [1,2,3]
list2 = [4,5,6]

arr1 = np.array(list1)
arr2 = np.array(list2)

In [11]:
list1+list2

[1, 2, 3, 4, 5, 6]

In [12]:
arr1+arr2

array([5, 7, 9])